DROP TABLE IF EXISTS pokemon_team CASCADE;
DROP TABLE IF EXISTS pokemon_move CASCADE;
DROP TABLE IF EXISTS pokemon_type CASCADE;
DROP TABLE IF EXISTS pokemon CASCADE;
DROP TABLE IF EXISTS random_pokemon CASCADE;
